/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    'blog-posts': BlogPost;
    faqs: Faq;
    testimonials: Testimonial;
    'case-studies': CaseStudy;
    'pricing-tiers': PricingTier;
    'site-settings': SiteSetting;
    'checkout-trust-experiences': CheckoutTrustExperience;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'pricing-tiers': PricingTiersSelect<false> | PricingTiersSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'checkout-trust-experiences': CheckoutTrustExperiencesSelect<false> | CheckoutTrustExperiencesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Marketing pages rendered by the Next.js frontend.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    subheadline?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  content?:
    | (
        | {
            layout?: ('two-column' | 'metrics' | 'case-study' | 'faq' | 'testimonials' | 'pricing' | 'blog') | null;
            heading?: string | null;
            subheading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            metrics?:
              | {
                  label?: string | null;
                  value?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            faqItems?: (number | Faq)[] | null;
            testimonials?: (number | Testimonial)[] | null;
            caseStudy?: (number | null) | CaseStudy;
            pricingTiers?: (number | PricingTier)[] | null;
            blogPosts?: (number | BlogPost)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            quote: string;
            author?: string | null;
            role?: string | null;
            company?: string | null;
            avatarUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial';
          }
      )[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  environment: 'development' | 'test' | 'production';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: string | null;
  environment: 'development' | 'test' | 'production';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author?: string | null;
  role?: string | null;
  company?: string | null;
  avatarUrl?: string | null;
  environment: 'development' | 'test' | 'production';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  client?: string | null;
  industry?: string | null;
  summary?: string | null;
  results?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  quote?: string | null;
  quoteAuthor?: string | null;
  environment: 'development' | 'test' | 'production';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-tiers".
 */
export interface PricingTier {
  id: number;
  name: string;
  description?: string | null;
  price?: number | null;
  currency?: string | null;
  features?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  highlight?: boolean | null;
  environment: 'development' | 'test' | 'production';
  updatedAt: string;
  createdAt: string;
}
/**
 * Long-form articles surfaced on the marketing site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  publishedAt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  environment: 'development' | 'test' | 'production';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  title: string;
  tagline?: string | null;
  heroCta?: {
    label?: string | null;
    href?: string | null;
  };
  environment: 'development' | 'test' | 'production';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-trust-experiences".
 */
export interface CheckoutTrustExperience {
  id: number;
  name: string;
  slug: string;
  guaranteeHeadline?: string | null;
  guaranteeDescription?: string | null;
  assurancePoints?:
    | {
        id?: string | null;
        title: string;
        description?: string | null;
        evidence?: string | null;
        metric?: {
          /**
           * Maps this module to a backend metric identifier.
           */
          metricId?: ('fulfillment_sla_on_time_pct' | 'first_response_minutes' | 'nps_trailing_30d') | null;
          /**
           * Signals where the metric originates for provenance badges.
           */
          metricSource?: ('fulfillment' | 'operator_staffing' | 'support_analytics') | null;
          /**
           * Maximum allowable staleness before the module shows a warning.
           */
          freshnessWindowMinutes?: number | null;
          /**
           * Operator console preview override for draft content.
           */
          previewState?: ('fresh' | 'stale' | 'missing') | null;
          /**
           * Optional context describing how this metric is produced.
           */
          provenanceNote?: string | null;
        };
      }[]
    | null;
  supportChannels?:
    | {
        id?: string | null;
        channel: string;
        label: string;
        target: string;
        availability?: string | null;
      }[]
    | null;
  performanceSnapshots?:
    | {
        id?: string | null;
        label: string;
        caption?: string | null;
        /**
         * Value displayed when live metric data is unavailable.
         */
        fallbackValue?: string | null;
        metric?: {
          /**
           * Maps this module to a backend metric identifier.
           */
          metricId?: ('fulfillment_sla_on_time_pct' | 'first_response_minutes' | 'nps_trailing_30d') | null;
          /**
           * Signals where the metric originates for provenance badges.
           */
          metricSource?: ('fulfillment' | 'operator_staffing' | 'support_analytics') | null;
          /**
           * Maximum allowable staleness before the module shows a warning.
           */
          freshnessWindowMinutes?: number | null;
          /**
           * Operator console preview override for draft content.
           */
          previewState?: ('fresh' | 'stale' | 'missing') | null;
          /**
           * Optional context describing how this metric is produced.
           */
          provenanceNote?: string | null;
        };
      }[]
    | null;
  testimonials?:
    | {
        id?: string | null;
        quote: string;
        author?: string | null;
        role?: string | null;
        /**
         * Optional audience segment tag used for personalization.
         */
        segment?: string | null;
      }[]
    | null;
  bundleOffers?:
    | {
        id?: string | null;
        slug: string;
        title: string;
        description?: string | null;
        savings?: string | null;
      }[]
    | null;
  environment: 'development' | 'test' | 'production';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'pricing-tiers';
        value: number | PricingTier;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'checkout-trust-experiences';
        value: number | CheckoutTrustExperience;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subheadline?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  content?:
    | T
    | {
        section?:
          | T
          | {
              layout?: T;
              heading?: T;
              subheading?: T;
              content?: T;
              metrics?:
                | T
                | {
                    label?: T;
                    value?: T;
                    description?: T;
                    id?: T;
                  };
              faqItems?: T;
              testimonials?: T;
              caseStudy?: T;
              pricingTiers?: T;
              blogPosts?: T;
              id?: T;
              blockName?: T;
            };
        testimonial?:
          | T
          | {
              quote?: T;
              author?: T;
              role?: T;
              company?: T;
              avatarUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  environment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  publishedAt?: T;
  body?: T;
  environment?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  environment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  company?: T;
  avatarUrl?: T;
  environment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  industry?: T;
  summary?: T;
  results?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  quote?: T;
  quoteAuthor?: T;
  environment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-tiers_select".
 */
export interface PricingTiersSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  currency?: T;
  features?:
    | T
    | {
        value?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  highlight?: T;
  environment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  heroCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  environment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-trust-experiences_select".
 */
export interface CheckoutTrustExperiencesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  guaranteeHeadline?: T;
  guaranteeDescription?: T;
  assurancePoints?:
    | T
    | {
        id?: T;
        title?: T;
        description?: T;
        evidence?: T;
        metric?:
          | T
          | {
              metricId?: T;
              metricSource?: T;
              freshnessWindowMinutes?: T;
              previewState?: T;
              provenanceNote?: T;
            };
      };
  supportChannels?:
    | T
    | {
        id?: T;
        channel?: T;
        label?: T;
        target?: T;
        availability?: T;
      };
  performanceSnapshots?:
    | T
    | {
        id?: T;
        label?: T;
        caption?: T;
        fallbackValue?: T;
        metric?:
          | T
          | {
              metricId?: T;
              metricSource?: T;
              freshnessWindowMinutes?: T;
              previewState?: T;
              provenanceNote?: T;
            };
      };
  testimonials?:
    | T
    | {
        id?: T;
        quote?: T;
        author?: T;
        role?: T;
        segment?: T;
      };
  bundleOffers?:
    | T
    | {
        id?: T;
        slug?: T;
        title?: T;
        description?: T;
        savings?: T;
      };
  environment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}